package org.chat.model.db;
// Generated 29-nov-2016 10.27.11 by Hibernate Tools 4.3.1

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable, Comparable<Message> {

    private Long id;
    private String sender;
    private String receiver;
    private String text;
    private Boolean senderVisibility;
    private Boolean receiverVisibility;
    private Date datetime;

    private SimpleDateFormat today = new SimpleDateFormat("HH:mm");
    private SimpleDateFormat thisWeek = new SimpleDateFormat("EEEE", Locale.ENGLISH);
    private SimpleDateFormat date = new SimpleDateFormat("yyyy/MM/dd");

    public Message() {
    }

    public Message(String sender, String receiver, String text) {
        this.sender = sender;
        this.receiver = receiver;
        this.text = text;
        this.datetime = new Date();
        this.senderVisibility = true;
        this.receiverVisibility = true;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSender() {
        return this.sender;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }

    public String getReceiver() {
        return this.receiver;
    }

    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Boolean getSenderVisibility() {
        return this.senderVisibility;
    }

    public void setSenderVisibility(Boolean senderVisibility) {
        this.senderVisibility = senderVisibility;
    }

    public Boolean getReceiverVisibility() {
        return this.receiverVisibility;
    }

    public void setReceiverVisibility(Boolean receiverVisibility) {
        this.receiverVisibility = receiverVisibility;
    }

    public Date getDatetime() {
        return this.datetime;
    }

    public String getFormattedDate() {
        
        Date today = new Date();
        if (date.format(today).equals(date.format(datetime))) {
            return this.today.format(datetime);
        }

        Calendar c = Calendar.getInstance();
        c.add(Calendar.DATE, -1); //yesterday
        if (date.format(c.getTime()).equals(date.format(datetime))) {
            return "Yesterday";
        }
        
        c.add(Calendar.DATE, -6); //6 days ago
        if (datetime.after(c.getTime())) {
            return this.thisWeek.format(datetime);
        }
        
        return date.format(datetime);
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public void setUserVisibility(String username, Boolean visibility) {
        if (username.equalsIgnoreCase(this.getSender())) {
            this.setSenderVisibility(visibility);
        } else if (username.equalsIgnoreCase(this.getReceiver())) {
            this.setReceiverVisibility(visibility);
        }
    }

    @Override
    public int compareTo(Message o) {
        if (this.getDatetime() == null || o.getDatetime() == null) {
            return 0;
        }
        return o.getDatetime().compareTo(this.getDatetime());
    }
}
